### ISSUE TITLE
Need instructions for contributors

### ISSUE THREAD

**Issue by justin808** [turbolinks/turbolinks-source-gem#1]
Hi @sstephenson!

Any chance that you can publish some docs on how to hack on the Turbolinks gem locally. It's not obvious given how there's two repos for the gem.

We've forked both this repo and `turbolinks` and we need to update the Gemfile of our app appropriately, 

``` ruby
gem "turbolinks", path: "../turbolinks"
```

and I'm guessing we need to run `rake build` in this repo.

And we have to run `rake build` any time we change the coffeescript.

Any option to not have to re-build after every change.

**Comment by sstephenson** [comment]
Hey Justin,

Easiest way to hack on Turbolinks in a Rails app is to add the `src` directory to your asset paths in `config/application.rb`:

``` ruby
module Foo
  class Application < Rails::Application
    config.assets.paths.unshift("/path/to/turbolinks/src")
    # …
  end
end
```

Make sure you restart the app for the change to take effect.

(No need to mess with this gem, really. It’s just for distributing official releases.)

**Comment by justin808** [comment]
@sstephenson Thanks! Sounds great. Any other must-know tips for hacking on this?

BTW, did you consider writing this in ES6?
